COUNTRIES: ['', 'France', 'Argentina', 'Italy', 'Spain']

FILL: {
  'Appellation': '',
  'Sweetness': '',
  'Wine Type': '',
  'Closure': '',
  'Region': '',
  'Brand': '',
  'Body': '',
  'Oak': '',
}

france: 400
argentina: 100
italy: 400
spain: 314
